name: modul_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  sizer: ^2.0.15
  font_awesome_flutter: ^10.7.0
  curved_navigation_bar: ^1.0.6
  image_picker: ^1.0.8
  get_storage: ^2.1.1
  http: ^1.2.0
  intl: ^0.19.0
  appwrite: ^12.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

